name: flutter_emoji_feedback
description: A fully customizable widget to receive feedback from your users. Useful to get  the user's mood, evaluate their experience, and more!
version: 1.0.3
homepage: https://github.com/stevenosse/flutter_emoji_feedback
maintainer: Steve NOSSE

environment:
  sdk: '>3.1.5 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  flutter_svg: ^2.0.16
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.8.0

flutter:
  assets:
    - assets/

screenshots:
  - description: 'Animated emoji'
    path: demo.gif